import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

// We can define the expected token here for simple validation,
// or just check for the presence of the cookie.
// Since the token is generated by our worker and stored as HttpOnly,
// its presence is generally enough for this simple dashboard.
// If you want to strictly match it, set NEXT_PUBLIC_AUTH_TOKEN in .env.local

export function middleware(request: NextRequest) {
  const apiUrl = request.cookies.get("api_url")?.value;
  
  // Public paths that don't require authentication
  const publicPaths = ["/login", "/demo", "/live-demo", "/favicon.ico", "/_next"];
  const isPublicPath = publicPaths.some((path) => request.nextUrl.pathname.startsWith(path));

  if (!apiUrl && !isPublicPath) {
    // Redirect to login if unauthenticated and trying to access a protected route
    return NextResponse.redirect(new URL("/login", request.url));
  }

  if (apiUrl && request.nextUrl.pathname === "/login") {
    // Redirect to home if already authenticated and trying to access login
    return NextResponse.redirect(new URL("/", request.url));
  }

  return NextResponse.next();
}

export const config = {
  // Apply middleware to all routes except API, static files, and images
  matcher: [
    "/((?!api|_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)"
  ],
};
